site_name: Mangum
site_description: Serverless ASGI adapters.

theme:
    name: 'material'
    palette:
      primary: 'brown'
      accent: 'orange'
    logo:
      icon: 'cloud'


repo_name: erm/mangum
repo_url: https://github.com/erm/mangum
edit_uri: ""

nav:
    - Introduction: 'index.md'
    - 'azure-how-to.md'
    - 'aws-how-to.md'

markdown_extensions:
  - markdown.extensions.codehilite:
      guess_lang: false

